### ISSUE TITLE
casino fails to build

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/enowars3-service-casino#4]
```
Mar 25 16:37:42 buster docker-compose[30211]: Step 14/20 : RUN julia pkgInstallation.jl
Mar 25 16:37:42 buster docker-compose[30211]:  ---> Running in e0365174bf41
Mar 25 16:37:42 buster docker-compose[30211]: ERROR: Unable to find compatible target in system image.
Mar 25 16:37:43 buster docker-compose[30211]: Service 'julias_casino' failed to build: The command '/bin/sh -c julia pkgInstallation.jl' returned a non-zero code: 1
```
cc @DopeforHope

**Comment by DopeforHope** [comment]
Hmm, builds on my system. Ubuntu 18.04 underneath.


https://github.com/JuliaLang/PackageCompilerX.jl/issues/106
A similar bug is described in this issue.

What is your OS?

**Comment by Trolldemorted** [comment]
debian10 iirc, maybe enoblade1 is too old for julia?

**Comment by Trolldemorted** [comment]
casino indeed builds fine if your hardware is not ancient

**Comment by DopeforHope** [comment]
So what was the problem?

I mean it's more or less about Julia itself on ancient hardware.

**Comment by Trolldemorted** [comment]
I a fairly certain enoblade1 doesn't have certain x86 extensions which julia requires, but now we are building it in cloudhosted vulnboxes which do have them ¯\_(ツ)_/¯
